### ISSUE TITLE
About Pages

### ISSUE THREAD

**Issue by philsturgeon** [protect-earth/protect.earth#41]
Shove together a lorem ipsum About page which I can write up some text about why this site exists. This could be just a generic page with a header, so we can make a few more generic pages.

**Comment by ijpatricio** [comment]
Ok, I'll make this my next assignment.

@philsturgeon Can we divide this in two steps, so that nr 1 is very quick?

Step 1 - Generic page, that imports (literally ES import) the HTML content from a chosen file

Step 2 - Generic page, that retrieves content from the api? With markdown content, or even better a block builder. MD block + image block. Each block an async VueComponent, that can be resued anywhere on the site.

**Comment by philsturgeon** [comment]
Yeah please step 1 for now is great. We might not need 2 for a long time, I'm fine pushing to the frontend for now.

**Comment by philsturgeon** [comment]
I’ll make a new issue for api-based pages of the need comes up. :)
